test('test-row', executable('test-bin-row', test_src + files('row.cc'),
                            include_directories: include,
                            dependencies:        dependencies))

# test('test-grid', executable('test-bin-grid', src + files('grid.cc'),
#                              include_directories: include,
#                              dependencies:        dependencies))