name: Build

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - uses: actions/checkout@v6

      - name: Install dependencies
        run: pacman -Syu meson sdl3 sdl3_ttf

      - name: Configure
        run: meson setup target

      - name: Compile
        run: meson compile -C target
